# SPDX-FileCopyrightText: : 2017-2024 The PyPSA-Eur Authors
#
# SPDX-License-Identifier: CC0-1.0

run:
  prefix: 20250604_sysgfplots
  name:
  - Baseline
  - No_PTES
  - LowPTESCAPEX
  - HighPTESCAPEX
  - LowStandingLosses
  - HighStandingLosses
  - LowGroundWaterDepth
  - HighGroundWaterDepth
  - LowEtPRatio
  - HighEtPRatio
  scenarios:
    enable: true
    manual_file: config/scenarios.sysgf.yaml
    file: config/scenarios.automated.yaml
    reference: Baseline
    fix_foreign_reference_investments: true
  shared_resources:
    policy: base #stops recalculating
    exclude:
    - existing_heating.csv   # specify files which should not be shared between scenarios
    - costs
    - retrieve_cost   # This is necessary to save retrieve_cost_data_{year}.log in the correct folder
    - industry_sector_ratios
    - build_industry_sector_ratios   # This is necessary to save build_industry_sector_ratios_data.log in the correct folder
    - modify_existing_heating

foresight: myopic

scenario:
  ll:
  - vopt
  clusters:
  - 27 #current options: 27, 49
  opts:
  - ''
  sector_opts:
  - none
  planning_horizons:
  # - 2020
  # - 2025
  # - 2030
  # - 2035
  # - 2040
  - 2045

clustering:
  temporal:
    resolution_sector: 365H

adjustments:
  electricity: false
  sector:
    absolute:
      Store:
        urban central water pits:
          standing_loss: 0.00012121
        urban central water tanks:
          standing_loss: 0.00015476

wasserstoff_kernnetz:
  enable: false

sector:
  district_heating:
    potential: 0.5
    subnodes:
      enable: true
    limited_heat_sources:
      geothermal:
        ignore_missing_regions: true
  heat_pump_sources:
    urban central:
    - air
    - geothermal
    urban decentral:
    - air
    rural:
    - air
    - ground

solving:
  constraints:
    CCL: false
    EQ: false
    BAU: false
    SAFE: false
    efuel_export_ban: false
    limits_capacity_max: {}
    limits_capacity_min: {}
    limits_volume_max: {}
    limits_volume_min: {}
    limits_power_max: {}

plotting:
  dual_comparison:
    enable: true
    scenario_A: No_PTES
    scenario_B: Baseline
  sensitivities:
    enable: true
    reference: Baseline
    runs: [
      PTESCAPEX,
      StandingLosses,
      GroundWaterDepth,
      EtPRatio
    ]
  sysgf_summary:
    enable: true
    reference: Baseline
    runs: [
      No_PTES,
      Baseline,
      LowPTESCAPEX,
      HighPTESCAPEX,
      LowStandingLosses,
      HighStandingLosses,
      LowGroundWaterDepth,
      HighGroundWaterDepth,
      LowEtPRatio,
      HighEtPRatio
    ]
  save_png: true
  save_pdf: true
  override_tech_colors:
    urban central water tanks charger: "cornflowerblue"
    urban central water tanks discharger: "cornflowerblue"
    urban central water tanks: "cornflowerblue"
    urban central water pits charger: "blue"
    urban central water pits discharger: "blue"
    urban central water pits: "blue"
    urban central water tanks load: "cornflowerblue"
    urban central water tanks generation: "cornflowerblue"
    urban central water pits load: "blue"
    urban central water pits generation: "blue"
    urban central solid biomass CHP: "forestgreen"
    urban central solid biomass CHP CC: "palegreen"
    urban central lignite CHP: "grey"
    urban central coal CHP: "dimgrey"
    urban central oil CHP: "darkolivegreen"
    urban central H2 CHP: "purple"
    urban central geothermal heat direct utilisation: "olive"
    urban central geothermal heat pump: "khaki"
    urban central heat vent: "red"
    urban central resistive heater: "mediumaquamarine"
    urban central air heat pump: "gold"
    low-temperature heat for industry: "darkgrey"
    waste CHP: "plum"
    Fischer-Tropsch: "slateblue"

