# -*- coding: utf-8 -*-
# SPDX-FileCopyrightText: : 2017-2023 The PyPSA-Eur Authors
#
# SPDX-License-Identifier: MIT

Baseline:

Baseline_control:

LowDH:
  sector:
    district_heating:
      potential: 0.3
HighDH:
  sector:
    district_heating:
      potential: 0.8

Baseline_fix_foreign_investments_.01slack:
  run:
    scenarios:
      fix_foreign_investments:
        enable: true
        reference_scenario: Baseline
        slack: 0.0001

Baseline_fix_foreign_investments_.1slack:
  run:
    scenarios:
      fix_foreign_investments:
        enable: true
        reference_scenario: Baseline
        slack: 0.001

Baseline_fix_foreign_investments_1slack:
  run:
    scenarios:
      fix_foreign_investments:
        enable: true
        reference_scenario: Baseline
        slack: 0.01



PTES_DE_leq_0TWh:
  solving:
    constraints:
      limits_capacity_max:
        Store:
          urban central water pits:
            DE:
              2020: 0        
              2025: 0        
              2030: 0        
              2035: 0        
              2040: 0        
              2045: 0        

PTES_DE_leq_10TWh:
  solving:
    constraints:
      limits_capacity_max:
        Store:
          urban central water pits:
            DE:
              2020: 10000        
              2025: 10000        
              2030: 10000        
              2035: 10000        
              2040: 10000        
              2045: 10000        

PTES_DE_leq_3TWh:
  solving:
    constraints:
      limits_capacity_max:
        Store:
          urban central water pits:
            DE:
              2020: 3000        
              2025: 3000        
              2030: 3000        
              2035: 3000        
              2040: 3000        
              2045: 3000        

PTES_DE_leq_1TWh:
  solving:
    constraints:
      limits_capacity_max:
        Store:
          urban central water pits:
            DE:
              2020: 1000        
              2025: 1000        
              2030: 1000        
              2035: 1000        
              2040: 1000        
              2045: 1000        
              
No_PTES:
  adjustments:
    electricity: false
    sector:
      absolute:
        Store:
          urban central water pits:
            e_nom_max: 0
            
TES_DE_leq_0TWh:
  solving:
    constraints:
      limits_capacity_max:
        Store:
          urban central water pits:
            DE:
              2020: 0        
              2025: 0        
              2030: 0        
              2035: 0        
              2040: 0        
              2045: 0
          urban central water tanks:
            DE:
              2020: 0        
              2025: 0        
              2030: 0        
              2035: 0        
              2040: 0        
              2045: 0

LowPTESCAPEX:
  run:
    scenarios:
      fix_foreign_investments:
        enable: true
        slack: 0.0001
  adjustments:
    electricity: false
    sector:
      factor:
        Store:
          urban central water pits:
            capital_cost: 0.5
      absolute:
        Store:
          urban central water pits:
            standing_loss: 0.00012121
          urban central water tanks:
            standing_loss: 0.00015476

HighPTESCAPEX:
  run:
    scenarios:
      fix_foreign_investments:
        enable: true
        slack: 0.0001
  adjustments:
    electricity: false
    sector:
      factor:
        Store:
          urban central water pits:
            capital_cost: 2
      absolute:
        Store:
          urban central water pits:
            standing_loss: 0.00012121
          urban central water tanks:
            standing_loss: 0.00015476

LowStandingLosses:
  adjustments:
    electricity: false
    sector:
      absolute:
        Store:
          urban central water pits:
            standing_loss: 0

HighStandingLosses:
  adjustments:
    electricity: false
    sector:
      absolute:
        Store:
          urban central water pits:
            standing_loss: 0.0012121

LowGroundWaterDepth:
  sector:
    district_heating:
      subnodes:
        limit_ptes_potential:
          max_groundwater_depth: -25

HighGroundWaterDepth:
  sector:
    district_heating:
      subnodes:
        limit_ptes_potential:
          max_groundwater_depth: 0

LowEtPRatio:
  adjustments:
    electricity: false
    sector:
      factor:
        Link:
          urban central water pits charger:
            energy to power ratio: 0.5

HighEtPRatio:
  adjustments:
    electricity: false
    sector:
      factor:
        Link:
          urban central water pits charger:
            energy to power ratio: 2
