name: pypsa-de
channels:
- conda-forge
- bioconda
dependencies:
- python>=3.8
- pip

# Add additional packages only to pypsa-de specific section
# All other packages should be identical to pypsa-eur (in best case the same, otherwise
# maybe different pins)

# pypsa-de specific
- pycountry
- pyam>=2.0
- ruamel.yaml
- jpype1

# Inhouse packages
- pypsa<=0.31.0
- atlite>=0.2.9
- linopy
- powerplantmatching>=0.5.15,<0.6

# Dependencies of the workflow itself
- dask
- xlrd
- openpyxl
- seaborn
- snakemake-minimal<8.25 # See https://github.com/snakemake/snakemake/issues/3202
- memory_profiler
- yaml
- pytables
- lxml
- numpy
- pandas>=2.1
- geopandas>=1
- xarray>=2023.11.0
- rioxarray
- netcdf4
- networkx
- scipy
- glpk
- shapely>=2.0
- pyscipopt
- scip!=9.2.0 # dependency of pyscipopt, temporary fix
- matplotlib
- proj
- fiona
- country_converter
- geopy
- tqdm
- pytz
- tabula-py
- pyxlsb
- graphviz
- pre-commit

# Keep in conda environment when calling ipython
- ipython

# GIS dependencies:
- cartopy
- descartes
- rasterio==1.4.1
- libgdal-core<3.10.0 # rasterio>=1.4.2 needed for GDAL 3.10

- pip:
  - gurobipy
  - highspy<1.8
  - tsam>=2.3.1
  - snakemake-storage-plugin-http
  - snakemake-executor-plugin-slurm
  - snakemake-executor-plugin-cluster-generic
